name: flutter_sensors_android
description: Android implementation of the flutter_sensors plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    implements: flutter_sensors
    platforms:
      android:
        package: com.spindance.tutorial
        pluginClass: FlutterSensorsPlugin
        dartPluginClass: FlutterSensorsAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_sensors_platform_interface:
    path: ../flutter_sensors_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
