name: flutter_sensors
description: A federated plugin providing access to platform sensors
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_sensors_android
      ios:
        default_package: flutter_sensors_ios

dependencies:
  flutter:
    sdk: flutter
  flutter_sensors_android:
    path: ../flutter_sensors_android
  flutter_sensors_ios:
    path: ../flutter_sensors_ios
  flutter_sensors_platform_interface:
    path: ../flutter_sensors_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
